language: python

services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - pip install pytest

script:
    - pytest --ignore "chronos-ui"

deploy:
    provider: script
    script: bash build.sh
