version: 2.1

executors:
    docker-publisher:
      environment:
        IMAGE_NAME: simsemand/chronos
      docker:
        - image: circleci/buildpack-deps:stretch

jobs:
    build:
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker:
                docker_layer_caching: true
          - run: |
                bash .circleci/prebuild.sh
                git log -n 1 --format=format:"%h%n" HEAD > VERSION
                cp VERSION chronos-ui/src/VERSION
                source $BASH_ENV
                echo $TAG
                docker build -t $IMAGE_NAME:$TAG .
          - run:
                name: Archive Docker image
                command: docker save -o image.tar $IMAGE_NAME
          - persist_to_workspace:
                root: .
                paths:
                    - ./image.tar
    publish:
        executor: docker-publisher
        steps:
            - attach_workspace:
                at: /tmp/workspace
            - checkout
            - setup_remote_docker
            - run:
                name: Load archived Docker image
                command: docker load -i /tmp/workspace/image.tar
            - run:
                name: Publish Docker Image to Docker Hub
                command: |
                    bash .circleci/prebuild.sh
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    source $BASH_ENV
                    echo $TAG
                    docker push $IMAGE_NAME:$TAG
    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                name: Run pytest
                command: |
                    pip install -r requirements.txt
                    pip install pytest
                    pytest --ignore=chronos-ui --junitxml=test-results/junit.xml
            - store_test_results:
                path: test-results
            - store_artifacts:
                path: test-results



workflows:
    version: 2
    build:
        jobs:
        - build
        - test
        - publish:
            requires:
                - build
                - test

