name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "TAG=ghcr.io/${{ github.repository_owner }}/new-chronos:latest" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . -t $TAG

      - name: Push the Docker image
        run: docker push $TAG
