name: Reset Chronos Demo
on:
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * *

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl apps restart chronos-demo
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}